// I've created a function which generates a random value declared in the 'value' array
function computerPlay() {
    const value = ['rock', 'paper', 'scissors'];
    const randomValue = value[Math.floor(Math.random() * value.length)];
    return randomValue;
}

// 1. I've delclared as parameters playerSelection wich represents the input from the user
// and computerSelection which represents the random value generated by the computer
// 2. The input taken from the user may be case-insensitive
// 3. The user can enter only valid inputs which contain only the specified words(rock, paper or scissors)
// 4. The user plays against the computer and in the console is displayed the winner, the main logic is based
//  on rock beats scissors, scissors beats paper and paper beats rock
// 5. The result is displayed as a string with the winner or the loser.

// isInputValid is a function based on Regular Expressions logic that returns true of false
// if the input match the specified words or not
function isInputValid(playerSelection) {
    return /rock|paper|scissors/g.test(playerSelection);
}

let playerScore = 0;
let computerScore = 0;

function playRound(playerSelection, round) {
    console.log('Round ' + round);
    const computerSelection = computerPlay();
    console.log(`Your selection is : ${playerSelection}`);
    console.log(`PC selection is : ${computerSelection}`);
    if (isInputValid(playerSelection)) {
        if (playerSelection == computerSelection) {
            console.log('Draw!');
            playerScore += 1;
            computerScore += 1;
        } else if (playerSelection == 'rock' && computerSelection == 'scissors') {
            console.log(`You Won! ${playerSelection} beats ${computerSelection}`);
            playerScore += 1;
        } else if (playerSelection == 'scissors' && computerSelection == 'paper') {
            console.log(`You Won! ${playerSelection} beats ${computerSelection}`);
            playerScore += 1;
        } else if (playerSelection == 'paper' && computerSelection == 'rock') {
            console.log(`You Won! ${playerSelection} beats ${computerSelection}`);
            playerScore += 1;
        } else {
            console.log(`You Lose! ${computerSelection} beats ${playerSelection}`);
            computerScore += 1;
        }
    } else {
        console.log('Please enter a valid input!');
    }
}


function game() {
    for (let i = 0; i < 5; i++) {
        let playerSelection = prompt('Enter your option: rock, paper or scissors:').toLowerCase();
        playRound(playerSelection, i);
        if (!isInputValid(playerSelection)) {
            break;
        }
    }
    console.log(`Player: ${playerScore} & Computer ${computerScore}`);
    if (playerScore > computerScore) {
        console.log("You win the game!");
    } else if (playerScore < computerScore) {
        console.log("You lose the game!");
    } else {
        console.log("It's draw!");
    }
}

game();